package com.hgits.vo;
// Generated 2014-9-17 9:03:26 by Hibernate Tools 3.2.1.GA

import java.util.Date;




/**
 * TbLaneLogin generated by hbm2java
 */
public class LaneLogin  implements java.io.Serializable {


     private Short roadId;//路段编号
     private Short stationId;//收费站编号
     private String lane;//车道编号
     private Date jobstart;//上班时间
     private String groupTime="000000000";//班次(排班时定义)
     private int groupId=0;//班组(排班时定义)
     private Date infoGetTime=new Date(0);//排班时间(排班时定义)
     private String staff;//收费员员工号
     private Integer laneType;//车道类型
     private int jobNum;//班次号
     private Short violatInclose;//违章车数量

    public LaneLogin() {
    }

    public Short getRoadId() {
        return roadId;
    }

    public String getGroupTime() {
        return groupTime;
    }

    public void setGroupTime(String groupTime) {
        this.groupTime = groupTime;
    }

    public int getGroupId() {
        return groupId;
    }

    public void setGroupId(int groupId) {
        this.groupId = groupId;
    }

    public Date getInfoGetTime() {
        return infoGetTime;
    }

    public void setInfoGetTime(Date infoGetTime) {
        this.infoGetTime = infoGetTime;
    }

    public void setRoadId(Short roadId) {
        this.roadId = roadId;
    }

    public Short getStationId() {
        return stationId;
    }

    public void setStationId(Short stationId) {
        this.stationId = stationId;
    }

    public String getLane() {
        return lane;
    }

    public void setLane(String lane) {
        this.lane = lane;
    }

    public Date getJobstart() {
        return jobstart;
    }

    public void setJobstart(Date jobstart) {
        this.jobstart = jobstart;
    }

    public String getStaff() {
        return staff;
    }

    public void setStaff(String staff) {
        this.staff = staff;
    }

    public Integer getLaneType() {
        return laneType;
    }

    public void setLaneType(Integer laneType) {
        this.laneType = laneType;
    }

    public int getJobNum() {
        return jobNum;
    }

    public void setJobNum(int jobNum) {
        this.jobNum = jobNum;
    }

    public Short getViolatInclose() {
        return violatInclose;
    }

    public void setViolatInclose(Short violatInclose) {
        this.violatInclose = violatInclose;
    }

    @Override
    public String toString() {
        return "LaneLogin{" + "roadId=" + roadId + ", stationId=" + stationId + ", lane=" + lane + ", jobstart=" + jobstart + ", groupTime=" + groupTime + ", groupId=" + groupId + ", infoGetTime=" + infoGetTime + ", staff=" + staff + ", laneType=" + laneType + ", jobNum=" + jobNum + ", violatInclose=" + violatInclose + '}';
    }

}


