package com.hgits.vo;
// Generated 2014-9-17 9:03:26 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TbLaneLoginId generated by hbm2java
 */
public class LaneLoginId  implements java.io.Serializable {


     private Integer laneId;
     private Date loginTime;
     private String operatorNo;

    public LaneLoginId() {
    }

    public LaneLoginId(Integer laneId, Date loginTime, String operatorNo) {
       this.laneId = laneId;
       this.loginTime = loginTime;
       this.operatorNo = operatorNo;
    }
   
    public Integer getLaneId() {
        return this.laneId;
    }
    
    public void setLaneId(Integer laneId) {
        this.laneId = laneId;
    }
    public Date getLoginTime() {
        return this.loginTime;
    }
    
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }
    public String getOperatorNo() {
        return this.operatorNo;
    }
    
    public void setOperatorNo(String operatorNo) {
        this.operatorNo = operatorNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LaneLoginId) ) return false;
		 LaneLoginId castOther = ( LaneLoginId ) other; 
         
		 return (this.getLaneId()==castOther.getLaneId())
 && ( (this.getLoginTime()==castOther.getLoginTime()) || ( this.getLoginTime()!=null && castOther.getLoginTime()!=null && this.getLoginTime().equals(castOther.getLoginTime()) ) )
 && ( (this.getOperatorNo()==castOther.getOperatorNo()) || ( this.getOperatorNo()!=null && castOther.getOperatorNo()!=null && this.getOperatorNo().equals(castOther.getOperatorNo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getLaneId();
         result = 37 * result + ( getLoginTime() == null ? 0 : this.getLoginTime().hashCode() );
         result = 37 * result + ( getOperatorNo() == null ? 0 : this.getOperatorNo().hashCode() );
         return result;
   }   


}


