package ui;

import com.hgits.control.FontControl;
import com.hgits.util.UIUtils;
import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.Toolkit;

/**
 * ETC军车卡提示界面
 *
 * @author yili
 */
public class MilitaryVehHintJFrame extends javax.swing.JFrame {

    /**
     * Creates new form militaryVehHintJFrame
     */
    private MilitaryVehHintJFrame() {
        UIUtils.removeMinMaxClose(this);
        initComponents();
        init();
    }

    private static MilitaryVehHintJFrame militaryVehHintJFrame;

    /**
     * 获取唯一实例化对象
     *
     * @return 唯一实例化对象
     */
    public static synchronized MilitaryVehHintJFrame getSingleInstance() {
        if (militaryVehHintJFrame == null) {
            militaryVehHintJFrame = new MilitaryVehHintJFrame();
        }
        return militaryVehHintJFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        confirm = new javax.swing.JButton();
//        cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("提示");
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);

        contentPanel.setBackground(new java.awt.Color(204, 250, 189));
        contentPanel.setPreferredSize(new java.awt.Dimension(377, 184));

        confirm.setFont(new java.awt.Font("微软雅黑", 1, 16)); // NOI18N
        confirm.setText("确 定");

//        cancel.setFont(new java.awt.Font("微软雅黑", 1, 16)); // NOI18N
//        cancel.setText("取 消");

        jLabel1.setFont(new java.awt.Font("黑体", 1, 48)); // NOI18N
        jLabel1.setText("  军警车");

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGap(81, 81, 81))
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirm))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
                MilitaryVehHintJFrame frame = new MilitaryVehHintJFrame();
                MilitaryVehHintJFrame.setDefaultLookAndFeelDecorated(true);
//                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JButton cancel;
    private javax.swing.JButton confirm;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void init() {
        //容器设置布局
        contentPanel.setLayout(new BorderLayout(0, 0));
        //添加容器
        this.add(contentPanel);
        //大小及位置
        this.setBounds(0, 0, 377, 184);
        this.setLocationRelativeTo(null);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/ui/img/highway.png")));
        this.setFocusableWindowState(true);
    }

    /**
     * 初始化字体
     */
    public void initFont() {
        Font font48 = FontControl.getMyFont(48);
        jLabel1.setFont(font48);
        Font font16 = FontControl.getMyFont(16);
        confirm.setFont(font16);
//        cancel.setFont(font16);
    }

}
